// Generated by CoffeeScript 1.5.0
var cc, should;

should = require('should');

cc = require('../');

describe('BaseCommand', function() {
  it('should be ready when its dependencies are done', function(done) {
    var bc, d1, d2;
    d1 = new cc.BaseCommand();
    d2 = new cc.BaseCommand();
    bc = new cc.BaseCommand();
    bc.addDependency(d1);
    bc.addDependency(d2);
    bc.isReady(function(ready) {
      return ready.should.be.not.ok;
    });
    d1.run(function() {});
    d2.run(function() {});
    return bc.isReady(function(ready) {
      ready.should.be.ok;
      return done();
    });
  });
  return it('should not be ready when one its dependencies is not done', function(done) {
    var bc, d1, d2;
    d1 = new cc.BaseCommand();
    d2 = new cc.BaseCommand();
    bc = new cc.BaseCommand();
    bc.addDependency(d1);
    bc.addDependency(d2);
    d1.run(function() {});
    return bc.isReady(function(ready) {
      ready.should.be.not.ok;
      return done();
    });
  });
});
