// Generated by CoffeeScript 1.5.0
var cc, should;

should = require('should');

cc = require('../');

describe('FileFilter', function() {
  return it('should find the package.json file', function(done) {
    return cc.FileFilter.foreach('.', /\.json$/, function(filename) {
      return done();
    });
  });
});
