// Generated by CoffeeScript 1.5.0
var cc, should;

should = require('should');

cc = require('../');

describe('GitFetchCommand', function() {
  it('should update if the module already exists', function(done) {
    var sh1;
    sh1 = new cc.GitFetchCommand("ssh://not_interesting", "lib");
    return sh1.preRun(function(shouldRun) {
      shouldRun.should.be["true"];
      sh1.cmd.should.equal("git remote update");
      return done();
    });
  });
  it('should clone if the module does not exists', function(done) {
    var sh1;
    sh1 = new cc.GitFetchCommand("ssh://not_interesting", "lib2");
    return sh1.preRun(function(shouldRun) {
      shouldRun.should.be["true"];
      sh1.cmd.should.equal("git clone ssh://not_interesting lib2 && cd lib2");
      return done();
    });
  });
  return it('should checkout the correct branch', function(done) {
    var sh1;
    sh1 = new cc.GitFetchCommand("ssh://not_interesting", "lib2", "1.0");
    return sh1.preRun(function(shouldRun) {
      shouldRun.should.be["true"];
      sh1.cmd.should.equal("git clone ssh://not_interesting lib2 && cd lib2 && git checkout origin/1.0");
      return done();
    });
  });
});
