// Generated by CoffeeScript 1.4.0
var cc, should;

should = require('should');

cc = require('../');

describe('Group', function() {
  return it('should contain a list of commands', function(done) {
    var cco, d1, d2, d3, g;
    d1 = new cc.BaseCommand();
    d2 = new cc.BaseCommand();
    d3 = new cc.BaseCommand();
    g = new cc.Group("test-group");
    g.add(d1);
    g.add(d2);
    g.add(d3);
    cco = new cc.CommandController();
    cco.addCommand(d1);
    cco.addCommand(d2);
    cco.addCommand(d3);
    cco.addCommand(g);
    return cco.run(function() {
      g.done.should.be.ok;
      return done();
    });
  });
});
