// Generated by CoffeeScript 1.5.0
var BaseCommand;

BaseCommand = (function() {

  function BaseCommand(name) {
    this.name = name;
    this.dependencies = [];
    this.done = false;
  }

  BaseCommand.prototype.addDependency = function(dep) {
    return this.dependencies.push(dep);
  };

  BaseCommand.prototype.isReady = function(done) {
    var dependency, _i, _len, _ref;
    _ref = this.dependencies;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      dependency = _ref[_i];
      if (!dependency.done || (dependency.done && dependency.err)) {
        return done(false);
      }
    }
    return done(true);
  };

  BaseCommand.prototype.preRun = function(done) {
    return done(true);
  };

  BaseCommand.prototype.run = function(done) {
    this.done = true;
    return done();
  };

  return BaseCommand;

})();

module.exports = BaseCommand;
