// Generated by CoffeeScript 1.5.0
var extFilter, foreachFile, fs;

fs = require('fs');

foreachFile = function(folder, filter, done) {
  return fs.readdir(folder, function(err, files) {
    var file, _i, _len, _results;
    if (err) {
      console.log('ERROR', err);
      return;
    }
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      _results.push(filter(file, done));
    }
    return _results;
  });
};

extFilter = function(match) {
  return function(filename, done) {
    if (filename.match(match)) {
      return done(filename);
    }
  };
};

module.exports.foreach = foreachFile;

module.exports.ext = extFilter;
