// Generated by CoffeeScript 1.5.0
var foreachFile, fs;

fs = require('fs');

foreachFile = function(folder, match, done) {
  return fs.readdir(folder, function(err, files) {
    var file, _i, _len, _results;
    if (err) {
      console.log('ERROR', err);
      return;
    }
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      if (file.match(match)) {
        _results.push(done(file));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });
};

module.exports.foreach = foreachFile;
