// Generated by CoffeeScript 1.4.0
var FileUtils;

module.exports.BaseCommand = require('./basecommand');

module.exports.ShellCommand = require('./shellcommand');

module.exports.GitFetchCommand = require('./gitcommand');

module.exports.CommandController = require('./commandcontroller');

module.exports.Autotools = require('./autotools');

module.exports.Project = require('./project');

module.exports.FileFilter = require('./filefilter');

FileUtils = require('./fileutils');

module.exports.Copy = FileUtils.Copy;

module.exports.Move = FileUtils.Move;

module.exports.Delete = FileUtils.Delete;

module.exports.Zip = FileUtils.Zip;
