// Generated by CoffeeScript 1.4.0
var GitCommand, Project, ShellCommand, cc;

cc = require('./');

GitCommand = cc.GitFetchCommand;

ShellCommand = cc.ShellCommand;

Project = (function() {

  function Project(cco, module, uri) {
    this.cco = cco;
    this.module = module;
    this.uri = uri;
    this.git = new GitCommand(this.uri, this.module);
    this.buildConfigure();
    this.configure.addDependency(this.git);
    this.configure.logFile = "" + this.module + "_configure.log";
    this.make = new ShellCommand("make", this.module);
    this.make.addDependency(this.configure);
    this.make.logFile = "" + this.module + "_make.log";
    this.cco.addCommand(this.git);
    this.cco.addCommand(this.configure);
    this.cco.addCommand(this.make);
  }

  Project.prototype.buildConfigure = function() {
    return this.configure = new ShellCommand("./configure", this.module);
  };

  return Project;

})();

module.exports = Project;
